### ISSUE TITLE
Create README

### ISSUE THREAD

**Issue by ezl** [ezl/wodeveryday.com#59]
for spinning up the project for local dev and for production

**Comment by cb0806151** [comment]
@ezl context question about how you want to be able to spin this up. Do you want to be able to generate the database from the fixtures file or would you prefer instructions on how to connect your local copy of the application to the remote database? 

The reason I ask is because the database is changing with every sprint; new fields being added, new data being stored, etc. Connecting to the remote database eliminates the sporadic need to update the fixtures files to keep them up-to-date

**Comment by cb0806151** [comment]
@ezl I updated the [README](https://github.com/ezl/wodeveryday.com) and will send you the .env file that it references. Let me know if the setup instructions work on your side

**Comment by cb0806151** [comment]
@ezl I had to update the [README](https://github.com/ezl/wodeveryday.com/blob/master/README.md) again. DEBUG and a few other values needed to be changed for production so using a local_settings files allows that to be circumvented without disrupting the application when running locally
