### ISSUE TITLE
Alt Tags

### ISSUE THREAD

**Issue by inflameous48** [ezl/wodeveryday.com#60]
We are going to have alt tags for 2 types of images:

First one is for the logo of the Gym:
![image](https://user-images.githubusercontent.com/50846999/83958145-0fed3580-a877-11ea-9c0b-b681a320b745.png)
In this case, the structure is going to look like this 
**alt="{gym name}"** 
so in the example above, their logo would be tagged the following way 
**alt="CrossFit Central Houston"**
**NOTE:** if we don't have the logo for a gym, and instead only have the default one (the devil clown?) just skip the tagging

The second one is for the images scraped for the gym
![image](https://user-images.githubusercontent.com/50846999/83958172-580c5800-a877-11ea-9665-35973c198634.png)
For this type of images, the structure is going to look like this 
**alt="Photo of {gym name} in {city}, {state(if applicable)},[country}"**
based on the first example it would look like this: 
**alt="Photo of CrossFit Central Houston in Houston, Texas, United States"**

**Comment by cb0806151** [comment]
Caveat: since some of these images are applied to vuetify cards they are given aria-labels instead of alt tags. This change falls in line with accessibility guidelines specified under the `techniques` tab here
https://fae.disability.illinois.edu/rulesets/IMAGE_1/#:~:text=The%20alt%20attribute%20is%20the,for%20img%20and%20area%20elements.&text=The%20aria%2Dlabel%20attribute%20should,role%3D%22img%22%20attribute.

**Comment by ezl** [comment]
sounds good to me. closing.
